site_name: CatPack Crafter docs
site_description: Documentation for the CatPack Crafter.
site_author: KTrain5369
copyright: Copyright 2024 by KTrain5369

repo_name: GitHub source
repo_url: https://github.com/KTrain5169/CatPackMaker
edit_uri: blob/main/docs/

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: # Chosen by https://discord.com/channels/1031648380885147709/1031694870756204566/1297376138888216647
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: orange
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KTrain5169
    - icon: fontawesome/brands/discord
      link: https://discord.gg/G6YvWhctjk
    - icon: fontawesome/brands/bluesky
      link: https://bsky.social/profile/ktrain5369.me

nav:
  - Home: index.md
  - Download: downloads.md
  - How to use: instructions.md
  - Contributing: contributing.md
  - Run from source: run-from-source.md

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search