site_name: CatPack Crafter docs
repo_name: GitHub source
repo_url: https://github.com/KTrain5169/CatPackMaker
edit_uri: blob/main/docs/
site_description: Documentation for the CatPack Crafter.
site_author: KTrain5369
theme: 
  name: material
nav:
  - Home: index.md
  - Download: downloads.md
  - How to use: instructions.md
  - Contributing: contributing.md