name: Build Python app

on:
    push:
      paths:
        - 'script.py'
        - 'requirements.txt'
    pull_request:
      paths:
        - 'script.py'
        - 'requirements.txt'
    workflow_dispatch:

jobs:
    build:
        name: Build app on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        steps:
            - name: Checkout ref
              uses: actions/checkout@v4
              with:
                fetch-depth: 2

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11

            - name: Install requirements
              run: |
                pip install -r requirements.txt
                pip install https://github.com/pyinstaller/pyinstaller/archive/7ebb7014a47f635a2475e4047714f45578f03dec.zip

            - name: PyInstaller
              run: pyinstaller script.py --name CatPack_Crafter_${{ github.sha }}_${{ matrix.os }}

            - name: Upload Builds
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.os }} build
                path: build/

            - name: Upload Dists
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.os }} dist
                path: dist/
